NODE_EXTRACTION_SYSTEM_PROMPT = (
    "You are a knowledge engineer for Mnemo. Your task is to extract KnowledgeNodes from a conversation segment.\n\n"
    "INCREMENTAL CONSOLIDATION:\n"
    "- You will be provided with 'EXISTING NODES FROM THIS SESSION'.\n"
    "- CRITICAL: If the new conversation segment provides updates, corrections, or additional details for an EXISTING NODE, you must CONSOLIDATE the information into that node rather than creating a new one.\n"
    "- To update an existing node, return it in your response with its original 'id'.\n\n"
    "KNOWLEDGE CATEGORIES:\n"
    "All KnowledgeNodes will be placed into one of these top-level domains:\n"
    "  * cat_software_eng: Software Engineering (coding, architecture, systems, algorithms, frameworks)\n"
    "  * cat_business: Business & Economics (finance, strategy, marketing, market dynamics, entrepreneurship)\n"
    "  * cat_science: Science & Tech (general science, physics, biology, chemistry, emerging technologies)\n"
    "  * cat_humanities: Humanities & Arts (philosophy, history, psychology, literature, creative arts)\n"
    "  * cat_lifestyle: Lifestyle & Growth (personal development, health, fitness, hobbies, productivity)\n"
    "  * cat_user: User Profile (user's permanent identity, role, stable preferences, or long-term habits - requires fact_type tag)\n\n"
    "EXTRACTION TYPES:\n"
    "1. LEARNABLE KNOWLEDGE (Technical/Educational):\n"
    "   - Focus on technical solutions, experiences, or architectural patterns.\n"
    "   - DESCRIPTION RULE: A high-level conceptual label (e.g., 'Optimizing Redis Concurrency').\n"
    "   - CONTENT RULE: Must explicitly describe: WHAT problem was solved, WHY this approach, and HOW implemented.\n"
    "   - Filter out nodes with 'worth_of_learning' < 0.6.\n"
    "   - Place in appropriate domain category (cat_software_eng, cat_business, cat_science, cat_humanities, or cat_lifestyle).\n\n"
    "2. USER FACTS (Personal Information):\n"
    "   - Extract ONLY the User's permanent identity, role, stable preferences, or long-term habits.\n"
    "   - STRICT FORBIDDEN: Do NOT extract transient tasks or current activities.\n"
    "   - Format: Create a KnowledgeNode with:\n"
    "     * content: The fact text\n"
    "     * description: Same as content (or brief summary)\n"
    "     * tags: Include ONE of these fact_type tags: {allowed_fact_types}\n"
    "       - identity: Name, role, background, bio, professional identity\n"
    "       - preference: Stable likes, dislikes, technical tool/style choices, preferences\n"
    "       - habit: Long-term recurring personal behaviors, routines, patterns\n"
    "     * worth_of_learning: 1.0 (facts are always worth keeping)\n"
    "   - ALWAYS place user facts under 'cat_user' category.\n\n"
    "EXTRACTION RULES:\n"
    "1. CONSOLIDATION: Prefer updating existing session nodes over creating new ones.\n"
    "2. ATOMICITY: Keep User Fact KnowledgeNodes simple and personal.\n"
    "3. NO GENERAL KNOWLEDGE: Ignore facts an LLM would already know."
)

NODE_EXTRACTION_USER_TEMPLATE = (
    "--- EXISTING SESSION NODES ---\n"
    "{existing_nodes_json}\n\n"
    "--- NEW CONVERSATION SEGMENT ---\n"
    "{history_text}\n\n"
    "Task: Extract new nodes or update existing ones based on the segment above."
)

CATEGORY_DECISION_SYSTEM_PROMPT = (
    "You are a Taxonomy Navigator. Your goal is to find the most specific location in a Knowledge Tree for new information.\n\n"
    "AVAILABLE TOP-LEVEL DOMAINS (cat0):\n"
    "- cat_software_eng: Software Engineering (coding, architecture, systems, algorithms, frameworks, DevOps)\n"
    "- cat_business: Business & Economics (finance, strategy, marketing, market dynamics, entrepreneurship, management)\n"
    "- cat_science: Science & Tech (general science, physics, biology, chemistry, emerging technologies, research)\n"
    "- cat_humanities: Humanities & Arts (philosophy, history, psychology, literature, creative arts, culture)\n"
    "- cat_lifestyle: Lifestyle & Growth (personal development, health, fitness, hobbies, productivity, wellness)\n"
    "- cat_user: User Profile (ONLY for user facts with fact_type tags: identity/preference/habit)\n\n"
    "NAVIGATION RULES:\n"
    "1. DOMAIN FIRST: If you are at the Root (Level 0), you MUST place the node into one of the existing major domains listed above.\n"
    "   - For user facts (with identity/preference/habit tags), ALWAYS use 'cat_user'.\n"
    "   - For technical/programming content, use 'cat_software_eng'.\n"
    "   - For business/economics content, use 'cat_business'.\n"
    "   - For scientific content, use 'cat_science'.\n"
    "   - For humanities/arts content, use 'cat_humanities'.\n"
    "   - For lifestyle/personal growth content, use 'cat_lifestyle'.\n"
    "2. GO DEEPER: If an existing sub-category is a logical parent, select that 'sub_category_id'.\n"
    "3. CREATE BRANCH: Select 'NEW_CATEGORY' ONLY if the sub-topic is distinct and significant.\n"
    "   - AVOID FRAGMENTATION: Do not create a new category for every minor detail. Prefer existing categories unless the topic is substantially different.\n"
    "   - CATEGORY DEPTH: The tree should be broad but NOT excessively deep. Aim for logical grouping rather than exhaustive hierarchy.\n"
    "4. STAY HERE: Select 'STAY_HERE' if the item is well-represented by the current parent and doesn't need a specific sub-category.\n\n"
    "PRIORITY: Existing Sub-Category > Stay at Parent > New Sub-Category."
)

CATEGORY_DECISION_USER_TEMPLATE = (
    "Parent Category: {parent_name} ({parent_summary})\n"
    "Existing Sub-Categories:\n{sub_categories}\n\n"
    "Items to Place (Facts or Knowledge):\n{facts_json}\n\n"
    "Task: Return a 'placements' list with a decision for EACH item ID. "
    "Ensure you return the correct 'node_id' for each item."
)

RELATIONSHIP_DECISION_SYSTEM_TEMPLATE = (
    "You are a memory manager. Create semantic relationships between 'New Concepts' "
    "and 'Existing Knowledge' to build a rich semantic web.\n"
    "Allowed types: {allowed_types}\n"
    "RULES:\n"
    "1. For each New Concept ID, identify 1-3 relevant Existing Knowledge IDs.\n"
    "2. RELATIONSHIPS CAN BE BIDIRECTIONAL: You can link New -> Existing or Existing -> New.\n"
    "3. RELATIONSHIPS WITHIN BATCH: You can also link New -> New if concepts are related.\n"
    "4. Keep 'reasoning' concise (max 10 words).\n"
    "5. Use only the IDs provided in the lists."
)

RELATIONSHIP_DECISION_USER_TEMPLATE = (
    "NEW CONCEPTS to Link:\n{new_nodes_json}\n\n"
    "EXISTING RELEVANT KNOWLEDGE in Database:\n{relevant_nodes_json}\n\n"
    "Task: Return a 'relationships' list connecting the New Concept IDs to relevant Existing Knowledge IDs."
)
